package com.kebablocator.android.models

import android.location.Location
import com.google.gson.annotations.SerializedName
import java.util.Calendar

// MARK: - Kebab Category Enum

enum class KebabCategory(val displayName: String, val emoji: String, val iconName: String) {
    DONER("D\u00F6ner", "\uD83E\uDD59", "local_fire_department"),
    FALAFEL("Falafel", "\uD83E\uDDC6", "eco"),
    DURUM("D\u00FCr\u00FCm", "\uD83C\uDF2F", "receipt_long"),
    SHAWARMA("Shawarma", "\uD83E\uDD69", "groups"),
    MIXED("Mixed Plate", "\uD83C\uDF7D\uFE0F", "takeout_dining");

    companion object {
        fun fromDisplayName(name: String): KebabCategory {
            return entries.firstOrNull { it.displayName.equals(name, ignoreCase = true) } ?: MIXED
        }
    }
}

// MARK: - Filter Option Enum

enum class FilterOption(val displayName: String, val iconName: String) {
    ALL("All", "local_fire_department"),
    OPEN_NOW("Open Now", "schedule"),
    TOP_RATED("Top Rated", "star"),
    DONER("D\u00F6ner", "restaurant"),
    FALAFEL("Falafel", "eco"),
    DURUM("D\u00FCr\u00FCm", "receipt_long"),
    SHAWARMA("Shawarma", "takeout_dining"),
    LATE_NIGHT("Late Night", "nightlight"),
    DELIVERY("Delivery", "delivery_dining"),
    BUDGET("Budget", "euro"),
    DINE_IN("Dine-In", "chair")
}

// MARK: - Sort Option Enum

enum class SortOption(val displayName: String, val iconName: String) {
    DISTANCE("Distance", "location_on"),
    RATING("Rating", "star"),
    PRICE("Price", "euro"),
    NAME("Name", "sort_by_alpha")
}

// MARK: - Kebab Shop Data Class

data class KebabShop(
    val id: String,
    val name: String,
    val rating: Double,
    val reviews: Int,
    val address: String,
    val latitude: Double,
    val longitude: Double,
    val tags: List<String>,
    val price: String,
    val hours: String,
    val openHour: Int,
    val closeHour: Int,
    val description: String,
    val imageName: String,
    val category: KebabCategory,
    val phone: String,
    val website: String,
    val popularDishes: List<String>,
    val hasDelivery: Boolean,
    val hasDineIn: Boolean,
    val hasTakeaway: Boolean,
    val isSponsored: Boolean = false,
    val isVerified: Boolean = false,
    val contributorId: String? = null,
    val imageUrl: String? = null
) {

    /** Check if the shop is currently open based on device time */
    val isOpenNow: Boolean
        get() {
            val hour = Calendar.getInstance().get(Calendar.HOUR_OF_DAY)
            return if (closeHour > openHour) {
                hour >= openHour && hour < closeHour
            } else {
                hour >= openHour || hour < closeHour
            }
        }

    /** Formatted open status string */
    val statusText: String
        get() = if (isOpenNow) "Open Now" else "Closed"

    /** Distance from a given coordinate in kilometers using Location.distanceBetween */
    fun distanceFrom(lat: Double, lon: Double): Double {
        val results = FloatArray(1)
        Location.distanceBetween(latitude, longitude, lat, lon, results)
        return results[0].toDouble() / 1000.0 // convert metres to km
    }

    /** Returns the best available image URL string for display */
    fun displayImageURL(): String? {
        if (!imageUrl.isNullOrEmpty() && imageUrl.startsWith("http")) {
            return imageUrl
        }
        if (imageName.startsWith("http")) {
            return imageName
        }
        return null
    }

    // MARK: - Sample Data

    companion object {
        val sampleData: List<KebabShop> = listOf(
            KebabShop(
                id = "1",
                name = "Zahir Kebab",
                rating = 4.8,
                reviews = 1243,
                address = "Av. Almirante Reis 11B, Lisboa",
                latitude = 38.7230,
                longitude = -9.1355,
                tags = listOf("Legendary", "Lamb", "Late Night"),
                price = "\u20AC\u20AC",
                hours = "11:00 \u2013 04:00",
                openHour = 11,
                closeHour = 4,
                description = "Widely considered by locals as one of the best spots in Lisbon. They actually marinate their lamb properly instead of using frozen minced meat blocks. The garlic sauce is intense.",
                imageName = "kebab1",
                category = KebabCategory.DONER,
                phone = "+351 21 814 1234",
                website = "",
                popularDishes = listOf("Lamb D\u00F6ner", "Spicy Chicken Box", "Ayran"),
                hasDelivery = true,
                hasDineIn = true,
                hasTakeaway = true
            ),
            KebabShop(
                id = "2",
                name = "Lebanese Corner",
                rating = 4.9,
                reviews = 892,
                address = "Largo do Rato 4, Lisboa",
                latitude = 38.7202,
                longitude = -9.1540,
                tags = listOf("Lebanese", "Premium", "Fresh"),
                price = "\u20AC\u20AC\u20AC",
                hours = "12:00 \u2013 22:30",
                openHour = 12,
                closeHour = 22,
                description = "A step up in quality. Slightly pricier, but they use grilled red peppers, fresh red onion, and real harissa. The shawarma is tender and the homemade pita holds everything together perfectly.",
                imageName = "kebab2",
                category = KebabCategory.SHAWARMA,
                phone = "+351 21 387 5555",
                website = "lebanesecorner.pt",
                popularDishes = listOf("Beef Shawarma Wrap", "Hummus with Pine Nuts", "Falafel Plate"),
                hasDelivery = true,
                hasDineIn = true,
                hasTakeaway = true
            ),
            KebabShop(
                id = "3",
                name = "Turkish Kebab House",
                rating = 4.6,
                reviews = 2104,
                address = "Rua do Benformoso 160, Lisboa",
                latitude = 38.7188,
                longitude = -9.1350,
                tags = listOf("Authentic", "Halal", "Busy"),
                price = "\u20AC",
                hours = "10:30 \u2013 02:00",
                openHour = 10,
                closeHour = 2,
                description = "A staple in the Intendente area. Massive portions, cheap prices, and very friendly staff. Their mixed D\u00FCr\u00FCm is heavy enough to skip dinner.",
                imageName = "kebab3",
                category = KebabCategory.DURUM,
                phone = "+351 91 123 4567",
                website = "",
                popularDishes = listOf("Mixed Meat D\u00FCr\u00FCm", "Chicken Shish", "Baklava"),
                hasDelivery = true,
                hasDineIn = false,
                hasTakeaway = true
            ),
            KebabShop(
                id = "4",
                name = "Mezze",
                rating = 4.8,
                reviews = 1560,
                address = "Mercado de Arroios, Lisboa",
                latitude = 38.7320,
                longitude = -9.1340,
                tags = listOf("Middle Eastern", "Social Project", "Charcoal Grill"),
                price = "\u20AC\u20AC",
                hours = "12:00 \u2013 22:00",
                openHour = 12,
                closeHour = 22,
                description = "More than just a kebab joint, this is a restaurant run by Syrian refugees. The food is staggeringly good\u2014try the baba ganoush alongside a real charcoal chicken kebab. Always packed.",
                imageName = "kebab4",
                category = KebabCategory.MIXED,
                phone = "+351 21 000 0000",
                website = "mezze.pt",
                popularDishes = listOf("Shish Taouk", "Baba Ganoush", "Fatoush Salad"),
                hasDelivery = false,
                hasDineIn = true,
                hasTakeaway = true
            ),
            KebabShop(
                id = "5",
                name = "Alibaba Kebab House",
                rating = 4.3,
                reviews = 940,
                address = "Rua da Palma 240, Martim Moniz",
                latitude = 38.7161,
                longitude = -9.1352,
                tags = listOf("Fast", "Halal", "Cheap"),
                price = "\u20AC",
                hours = "11:00 \u2013 05:00",
                openHour = 11,
                closeHour = 5,
                description = "The classic post-night-out lifesaver right by Martim Moniz. It's fast, greasy in a good way, and the guys behind the counter are impressively quick even at 4 AM.",
                imageName = "kebab5",
                category = KebabCategory.DONER,
                phone = "+351 93 456 7890",
                website = "",
                popularDishes = listOf("Chicken D\u00F6ner in Pita", "Fries with Sauce", "Falafel"),
                hasDelivery = true,
                hasDineIn = false,
                hasTakeaway = true
            ),
            KebabShop(
                id = "6",
                name = "Istanbul Kebab Baixa",
                rating = 4.4,
                reviews = 1820,
                address = "Rua das Portas de Santo Ant\u00E3o 52",
                latitude = 38.7155,
                longitude = -9.1400,
                tags = listOf("Central", "Family Friendly"),
                price = "\u20AC\u20AC",
                hours = "11:00 \u2013 00:00",
                openHour = 11,
                closeHour = 0,
                description = "Solid spot right in the tourist center but maintains good quality. Their Iskender Kebab with the hot tomato sauce and melted butter over pita bread is incredible.",
                imageName = "kebab6",
                category = KebabCategory.MIXED,
                phone = "+351 21 342 0987",
                website = "istanbulkebab.pt",
                popularDishes = listOf("Iskender Kebab", "Lahmacun", "Veal D\u00F6ner"),
                hasDelivery = true,
                hasDineIn = true,
                hasTakeaway = true
            ),
            KebabShop(
                id = "7",
                name = "Halal Counter",
                rating = 4.5,
                reviews = 630,
                address = "Rua Dom Carlos I 45, Santos",
                latitude = 38.7075,
                longitude = -9.1550,
                tags = listOf("Student Spot", "Halal", "Crispy Falafel"),
                price = "\u20AC",
                hours = "12:00 \u2013 02:00",
                openHour = 12,
                closeHour = 2,
                description = "A tiny hole-in-the-wall near IADE and the Santos bars. The falafels are super green inside, very herby, and fried to order so they never feel soggy.",
                imageName = "kebab7",
                category = KebabCategory.FALAFEL,
                phone = "",
                website = "",
                popularDishes = listOf("Falafel Wrap", "Chicken Box", "Sweet Potato Fries"),
                hasDelivery = true,
                hasDineIn = false,
                hasTakeaway = true
            ),
            KebabShop(
                id = "8",
                name = "Pita Shoarma (Joshua's)",
                rating = 3.9,
                reviews = 3200,
                address = "Armaz\u00E9ns do Chiado, Food Court",
                latitude = 38.7110,
                longitude = -9.1398,
                tags = listOf("Mall Food", "Shoarma", "Chain"),
                price = "\u20AC\u20AC",
                hours = "10:00 \u2013 23:00",
                openHour = 10,
                closeHour = 23,
                description = "It's a shopping mall staple in Portugal. Not the traditional gritty kebab shop, but their garlic mayonnaise is legendary and the pita bread is surprisingly soft.",
                imageName = "kebab8",
                category = KebabCategory.SHAWARMA,
                phone = "+351 21 322 0000",
                website = "joshuashoarma.pt",
                popularDishes = listOf("Pita Shoarma Menu", "Veggie Pita", "Wedges"),
                hasDelivery = true,
                hasDineIn = true,
                hasTakeaway = true
            ),
            KebabShop(
                id = "9",
                name = "O Rei do Kebab - Alc\u00E2ntara",
                rating = 4.2,
                reviews = 450,
                address = "Cal\u00E7ada da Tapada 12, Alc\u00E2ntara",
                latitude = 38.7050,
                longitude = -9.1800,
                tags = listOf("Local", "Big Portions"),
                price = "\u20AC",
                hours = "11:30 \u2013 23:30",
                openHour = 11,
                closeHour = 23,
                description = "A local joint feeding university students from ISA. You get an immense amount of food for under 6 euros. The spicy sauce actually packs a punch.",
                imageName = "kebab9",
                category = KebabCategory.DURUM,
                phone = "+351 92 111 2222",
                website = "",
                popularDishes = listOf("Student D\u00FCr\u00FCm", "Kebab Plate with Rice", "Fries"),
                hasDelivery = true,
                hasDineIn = true,
                hasTakeaway = true
            ),
            KebabShop(
                id = "10",
                name = "Lisbon Caf\u00E9 & Shisha",
                rating = 4.1,
                reviews = 800,
                address = "Bairro Alto, Rua da Rosa 105",
                latitude = 38.7125,
                longitude = -9.1455,
                tags = listOf("Shisha", "Drinks", "Late Night"),
                price = "\u20AC\u20AC",
                hours = "18:00 \u2013 03:00",
                openHour = 18,
                closeHour = 3,
                description = "Come for the shisha and tea, stay for the kebab. It's darker and louder than a normal restaurant, but eating a D\u00F6ner while having a cold drink before clubbing is unmatched.",
                imageName = "kebab10",
                category = KebabCategory.DONER,
                phone = "+351 21 888 7777",
                website = "",
                popularDishes = listOf("Mixed Plate", "Mint Tea", "Chicken D\u00FCr\u00FCm"),
                hasDelivery = false,
                hasDineIn = true,
                hasTakeaway = false
            ),
            KebabShop(
                id = "11",
                name = "Zubir Churrasqueira Halal",
                rating = 4.8,
                reviews = 650,
                address = "Rua do Benformoso 182, Intendente",
                latitude = 38.7190,
                longitude = -9.1350,
                tags = listOf("Desi Fusion", "BBQ", "Hidden Gem"),
                price = "\u20AC",
                hours = "12:00 \u2013 23:00",
                openHour = 12,
                closeHour = 23,
                description = "Not a traditional D\u00F6ner place, but a fantastic Halal BBQ spot blending South Asian and Middle Eastern flavors. Their charcoal-grilled chicken tikka in a wrap rivals any kebab in the city.",
                imageName = "kebab1",
                category = KebabCategory.SHAWARMA,
                phone = "+351 96 555 4444",
                website = "",
                popularDishes = listOf("Chicken Tikka Roll", "Lamb Seekh Kebab", "Mango Lassi"),
                hasDelivery = true,
                hasDineIn = true,
                hasTakeaway = true
            ),
            KebabShop(
                id = "12",
                name = "Alif Kebab House",
                rating = 4.3,
                reviews = 540,
                address = "Rua Morais Soares 45",
                latitude = 38.7280,
                longitude = -9.1330,
                tags = listOf("Pizza & Kebab", "Family", "Halal"),
                price = "\u20AC",
                hours = "11:00 \u2013 01:00",
                openHour = 11,
                closeHour = 1,
                description = "A classic hybrid shop selling both pizzas and kebabs. The 'Kebab Pizza' is an absolute unit of a meal if you hate making choices.",
                imageName = "kebab2",
                category = KebabCategory.MIXED,
                phone = "+351 21 333 2222",
                website = "",
                popularDishes = listOf("Kebab Pizza", "D\u00F6ner Sandwich", "Garlic Bread"),
                hasDelivery = true,
                hasDineIn = true,
                hasTakeaway = true
            ),
            KebabShop(
                id = "13",
                name = "I Love Kebab",
                rating = 4.0,
                reviews = 890,
                address = "Campo Pequeno Shopping Center",
                latitude = 38.7420,
                longitude = -9.1450,
                tags = listOf("Mall", "Fast", "Clean"),
                price = "\u20AC\u20AC",
                hours = "11:00 \u2013 22:00",
                openHour = 11,
                closeHour = 22,
                description = "Modern, brightly lit, and very clean. The meat is slightly thicker cut. Good option if you're catching a movie or concert at Campo Pequeno.",
                imageName = "kebab3",
                category = KebabCategory.DONER,
                phone = "+351 21 999 8888",
                website = "ilovekebab.pt",
                popularDishes = listOf("Mega D\u00FCr\u00FCm", "Kebab Box with Rice", "Nuggets"),
                hasDelivery = true,
                hasDineIn = true,
                hasTakeaway = true
            ),
            KebabShop(
                id = "14",
                name = "Shawarma Royale",
                rating = 4.7,
                reviews = 320,
                address = "Rua de S\u00E3o Paulo 100, Cais do Sodr\u00E9",
                latitude = 38.7070,
                longitude = -9.1440,
                tags = listOf("Gourmet", "Shawarma", "Cocktails"),
                price = "\u20AC\u20AC\u20AC",
                hours = "18:00 \u2013 02:00",
                openHour = 18,
                closeHour = 2,
                description = "A trendy, upscale take on Middle Eastern street food. They serve craft cocktails alongside deeply spiced, slow-roasted beef shawarma in freshly baked saj bread.",
                imageName = "kebab4",
                category = KebabCategory.SHAWARMA,
                phone = "+351 21 444 3333",
                website = "shawarmaroyale.pt",
                popularDishes = listOf("Beef Shawarma Saj", "Truffle Hummus", "Pomegranate Margarita"),
                hasDelivery = true,
                hasDineIn = true,
                hasTakeaway = false
            ),
            KebabShop(
                id = "15",
                name = "Gra\u00E7a Kebab View",
                rating = 4.5,
                reviews = 410,
                address = "Largo da Gra\u00E7a",
                latitude = 38.7160,
                longitude = -9.1300,
                tags = listOf("Scenic", "Sunset", "Beers"),
                price = "\u20AC\u20AC",
                hours = "15:00 \u2013 01:00",
                openHour = 15,
                closeHour = 1,
                description = "Technically a small kiosk/shop near the Miradouro. Grab a falafel wrap, a cold Super Bock, and sit on the wall watching the sunset over the castle.",
                imageName = "kebab5",
                category = KebabCategory.FALAFEL,
                phone = "",
                website = "",
                popularDishes = listOf("Sunset Falafel Wrap", "Chicken Box", "Draft Beer"),
                hasDelivery = false,
                hasDineIn = false,
                hasTakeaway = true
            ),
            KebabShop(
                id = "16",
                name = "Sultan D\u00F6ner",
                rating = 4.2,
                reviews = 550,
                address = "Avenida de Roma 45",
                latitude = 38.7450,
                longitude = -9.1390,
                tags = listOf("Local", "Neighborhood", "Friendly"),
                price = "\u20AC",
                hours = "11:00 \u2013 23:00",
                openHour = 11,
                closeHour = 23,
                description = "A quiet neighborhood favorite in Avenidas Novas. The owner knows everyone by name and usually sneaks extra fries into the box.",
                imageName = "kebab6",
                category = KebabCategory.DONER,
                phone = "+351 21 777 6666",
                website = "",
                popularDishes = listOf("Classic D\u00F6ner", "Cheese Fries", "Baklava"),
                hasDelivery = true,
                hasDineIn = true,
                hasTakeaway = true
            ),
            KebabShop(
                id = "17",
                name = "Berlin Gem\u00FCse Kebab",
                rating = 4.8,
                reviews = 890,
                address = "Rua da Boavista 18, Cais do Sodr\u00E9",
                latitude = 38.7080,
                longitude = -9.1460,
                tags = listOf("German Style", "Roasted Veggies", "Trendy"),
                price = "\u20AC\u20AC",
                hours = "12:00 \u2013 00:00",
                openHour = 12,
                closeHour = 0,
                description = "Modeled entirely after Mustafa's in Berlin. They put roasted potatoes, carrots, and eggplant inside the kebab, topped with crumbled feta cheese and a squeeze of lemon.",
                imageName = "kebab7",
                category = KebabCategory.DONER,
                phone = "+351 91 888 7777",
                website = "berlingemuse.pt",
                popularDishes = listOf("Gem\u00FCse Chicken D\u00F6ner", "Halloumi Wrap", "Club Mate"),
                hasDelivery = true,
                hasDineIn = false,
                hasTakeaway = true
            ),
            KebabShop(
                id = "18",
                name = "O\u00E1sis Vegetariano",
                rating = 4.6,
                reviews = 340,
                address = "Picoas, Rua Andrade Corvo",
                latitude = 38.7300,
                longitude = -9.1480,
                tags = listOf("Vegan Only", "Healthy", "Lunch"),
                price = "\u20AC\u20AC",
                hours = "11:00 \u2013 16:00",
                openHour = 11,
                closeHour = 16,
                description = "Only open for lunch. Everything is plant-based. They do a 'fake meat' seitan kebab that is surprisingly incredibly spiced and textured. Highly popular with office workers.",
                imageName = "kebab8",
                category = KebabCategory.FALAFEL,
                phone = "+351 21 555 4444",
                website = "oasisveg.pt",
                popularDishes = listOf("Seitan D\u00FCr\u00FCm", "Falafel Salad", "Fresh Ginger Lemonade"),
                hasDelivery = true,
                hasDineIn = true,
                hasTakeaway = true
            ),
            KebabShop(
                id = "19",
                name = "Tariq's Halal Grill",
                rating = 4.4,
                reviews = 620,
                address = "Odivelas, Av. D. Dinis",
                latitude = 38.7900,
                longitude = -9.1800,
                tags = listOf("Suburbs", "Huge Portions", "Family"),
                price = "\u20AC",
                hours = "12:00 \u2013 23:00",
                openHour = 12,
                closeHour = 23,
                description = "A bit outside the center but worth the trip if you live nearby. Tariq piles the meat so high on the D\u00FCr\u00FCm that it's physically difficult to close it. Excellent value.",
                imageName = "kebab9",
                category = KebabCategory.DURUM,
                phone = "+351 21 222 1111",
                website = "",
                popularDishes = listOf("Monster D\u00FCr\u00FCm", "Samosas", "Mango Milkshake"),
                hasDelivery = true,
                hasDineIn = true,
                hasTakeaway = true
            ),
            KebabShop(
                id = "20",
                name = "Kebab & Co. Cascais",
                rating = 4.3,
                reviews = 510,
                address = "Cascais Centro, Largo Praia da Rainha",
                latitude = 38.6960,
                longitude = -9.4200,
                tags = listOf("Beach", "Touristy", "Clean"),
                price = "\u20AC\u20AC\u20AC",
                hours = "10:00 \u2013 00:00",
                openHour = 10,
                closeHour = 0,
                description = "Located right by the beach in Cascais. It's more expensive than Lisbon spots, but grabbing a D\u00F6ner box and eating it on the sand while watching the waves is a great experience.",
                imageName = "kebab10",
                category = KebabCategory.DONER,
                phone = "+351 21 888 9999",
                website = "",
                popularDishes = listOf("Beach Kebab Box", "Pita Falafel", "Sangria"),
                hasDelivery = true,
                hasDineIn = false,
                hasTakeaway = true
            ),
            // MARK: - Convenience Stores & Late Night Shops
            KebabShop(
                id = "21",
                name = "Casa da India - Late Night",
                rating = 4.5,
                reviews = 320,
                address = "Rua da Palma 145, Martim Moniz",
                latitude = 38.7158,
                longitude = -9.1355,
                tags = listOf("Indian", "Convenience", "Late Night", "24h", "All Night"),
                price = "\u20AC",
                hours = "00:00 \u2013 24:00",
                openHour = 0,
                closeHour = 24,
                description = "Small Indian convenience store open 24 hours. Sells snacks, drinks, phone chargers, and basic groceries at any time of night. Popular with night shift workers and late-night party-goers.",
                imageName = "kebab1",
                category = KebabCategory.MIXED,
                phone = "+351 91 234 5678",
                website = "",
                popularDishes = listOf("Samosa", "Indian Snacks", "Energy Drinks"),
                hasDelivery = false,
                hasDineIn = false,
                hasTakeaway = true
            ),
            KebabShop(
                id = "22",
                name = "SPAR 24H Convenience",
                rating = 4.2,
                reviews = 890,
                address = "Av. Almirante Reis 88, Arroios",
                latitude = 38.7245,
                longitude = -9.1340,
                tags = listOf("Convenience", "24h", "Grocery", "All Night"),
                price = "\u20AC\u20AC",
                hours = "00:00 \u2013 24:00",
                openHour = 0,
                closeHour = 24,
                description = "24-hour convenience store with hot snacks, fresh coffee, sandwiches, and all essentials. ATM inside and accepts contactless payments.",
                imageName = "kebab2",
                category = KebabCategory.MIXED,
                phone = "+351 21 123 4567",
                website = "",
                popularDishes = listOf("Hot Dogs", "Fresh Coffee", "Sandwiches"),
                hasDelivery = false,
                hasDineIn = false,
                hasTakeaway = true
            ),
            KebabShop(
                id = "23",
                name = "Late Night Supermercado",
                rating = 4.0,
                reviews = 450,
                address = "Rua do Benformoso 200, Intendente",
                latitude = 38.7195,
                longitude = -9.1360,
                tags = listOf("Late Night", "Convenience", "24h", "Grocery"),
                price = "\u20AC",
                hours = "22:00 \u2013 08:00",
                openHour = 22,
                closeHour = 8,
                description = "Night-only convenience store serving the Intendente area. Open exclusively during night hours for shift workers and late crowds. Cheap snacks and drinks.",
                imageName = "kebab3",
                category = KebabCategory.MIXED,
                phone = "+351 92 345 6789",
                website = "",
                popularDishes = listOf("Chips", "Soft Drinks", "Cigarettes"),
                hasDelivery = false,
                hasDineIn = false,
                hasTakeaway = true
            ),
            KebabShop(
                id = "24",
                name = "Indian Mini Mart - Baixa",
                rating = 4.3,
                reviews = 280,
                address = "Rua da Prata 45, Baixa",
                latitude = 38.7075,
                longitude = -9.1380,
                tags = listOf("Indian", "Convenience", "Late Night"),
                price = "\u20AC",
                hours = "08:00 \u2013 02:00",
                openHour = 8,
                closeHour = 2,
                description = "Indian family-run convenience store in Baixa. Sells Indian spices, snacks, and late-night essentials. Known for their warm chai and friendly service even at 1 AM.",
                imageName = "kebab4",
                category = KebabCategory.MIXED,
                phone = "+351 93 456 7890",
                website = "",
                popularDishes = listOf("Masala Chai", "Indian Sweets", "Spices"),
                hasDelivery = false,
                hasDineIn = false,
                hasTakeaway = true
            ),
            KebabShop(
                id = "25",
                name = "All Night Shop - Cais do Sodr\u00E9",
                rating = 3.9,
                reviews = 670,
                address = "Rua de S\u00E3o Paulo 78, Cais do Sodr\u00E9",
                latitude = 38.7065,
                longitude = -9.1445,
                tags = listOf("All Night", "Convenience", "24h", "Party Area"),
                price = "\u20AC\u20AC",
                hours = "00:00 \u2013 24:00",
                openHour = 0,
                closeHour = 24,
                description = "The go-to spot for night owls in Cais do Sodr\u00E9. Open 24/7 with alcohol, snacks, phone chargers, and even umbrella rentals. Prices are higher but it's always open when you need it most.",
                imageName = "kebab5",
                category = KebabCategory.MIXED,
                phone = "+351 91 567 8901",
                website = "",
                popularDishes = listOf("Beer", "Chips", "Cigarettes"),
                hasDelivery = false,
                hasDineIn = false,
                hasTakeaway = true
            ),
            KebabShop(
                id = "26",
                name = "Mini Pre\u00E7o Express 24H",
                rating = 4.1,
                reviews = 520,
                address = "Av. da Liberdade 120",
                latitude = 38.7220,
                longitude = -9.1465,
                tags = listOf("Convenience", "24h", "Grocery", "All Night"),
                price = "\u20AC\u20AC",
                hours = "00:00 \u2013 24:00",
                openHour = 0,
                closeHour = 24,
                description = "24-hour mini supermarket on Avenida da Liberdade. Fresh bread delivery at 6 AM, hot coffee always available, and complete grocery selection even at 3 AM.",
                imageName = "kebab6",
                category = KebabCategory.MIXED,
                phone = "+351 21 789 0123",
                website = "",
                popularDishes = listOf("Fresh Bread", "Coffee", "Ready Meals"),
                hasDelivery = true,
                hasDineIn = false,
                hasTakeaway = true
            ),
            KebabShop(
                id = "27",
                name = "Bombay Corner Store",
                rating = 4.4,
                reviews = 340,
                address = "Rua do Benformoso 175, Intendente",
                latitude = 38.7192,
                longitude = -9.1358,
                tags = listOf("Indian", "Convenience", "Late Night"),
                price = "\u20AC",
                hours = "10:00 \u2013 04:00",
                openHour = 10,
                closeHour = 4,
                description = "Authentic Indian convenience store selling spices, Bollywood DVDs, Indian snacks, and phone accessories. Open until 4 AM for the late-night crowd. Bollywood music always playing.",
                imageName = "kebab7",
                category = KebabCategory.MIXED,
                phone = "+351 92 678 9012",
                website = "",
                popularDishes = listOf("Samosas", "Indian Sweets", "Chai"),
                hasDelivery = false,
                hasDineIn = false,
                hasTakeaway = true
            ),
            KebabShop(
                id = "28",
                name = "24H Gas Station Shop",
                rating = 3.8,
                reviews = 210,
                address = "Av. Bras\u00EDlia, Bel\u00E9m",
                latitude = 38.6950,
                longitude = -9.2050,
                tags = listOf("24h", "Convenience", "All Night", "Gas Station"),
                price = "\u20AC\u20AC",
                hours = "00:00 \u2013 24:00",
                openHour = 0,
                closeHour = 24,
                description = "24-hour convenience store attached to gas station. Hot dogs, coffee, energy drinks, and car essentials available around the clock.",
                imageName = "kebab8",
                category = KebabCategory.MIXED,
                phone = "+351 21 345 6789",
                website = "",
                popularDishes = listOf("Hot Dogs", "Coffee", "Snacks"),
                hasDelivery = false,
                hasDineIn = false,
                hasTakeaway = true
            ),
            KebabShop(
                id = "29",
                name = "Night Owl Convenience",
                rating = 4.0,
                reviews = 180,
                address = "Rua Nova do Carvalho 32, Pink Street",
                latitude = 38.7070,
                longitude = -9.1435,
                tags = listOf("Late Night", "Convenience", "Party Area"),
                price = "\u20AC\u20AC",
                hours = "20:00 \u2013 06:00",
                openHour = 20,
                closeHour = 6,
                description = "Night-only convenience store in Pink Street area. Opens at 8 PM and stays open until 6 AM specifically for the nightlife crowd. Energy drinks, snacks, and after-party essentials.",
                imageName = "kebab9",
                category = KebabCategory.MIXED,
                phone = "+351 91 789 0123",
                website = "",
                popularDishes = listOf("Energy Drinks", "Snacks", "Water"),
                hasDelivery = false,
                hasDineIn = false,
                hasTakeaway = true
            ),
            KebabShop(
                id = "30",
                name = "Desi Grocery & Snacks",
                rating = 4.5,
                reviews = 290,
                address = "Rua de Arroios 67",
                latitude = 38.7310,
                longitude = -9.1320,
                tags = listOf("Indian", "Convenience", "Late Night"),
                price = "\u20AC",
                hours = "09:00 \u2013 02:00",
                openHour = 9,
                closeHour = 2,
                description = "Indian grocery store with fresh samosas made daily, Indian spices, Bollywood magazines, and late-night snacks. Family-run business with authentic Indian products hard to find elsewhere.",
                imageName = "kebab10",
                category = KebabCategory.MIXED,
                phone = "+351 92 890 1234",
                website = "",
                popularDishes = listOf("Fresh Samosas", "Indian Sweets", "Spices"),
                hasDelivery = false,
                hasDineIn = false,
                hasTakeaway = true
            )
        )
    }
}

// MARK: - Supabase DTO for JSON Parsing

data class SupabaseShopDTO(
    @SerializedName("id") val id: String,
    @SerializedName("name") val name: String,
    @SerializedName("rating") val rating: Double,
    @SerializedName("reviews") val reviews: Int,
    @SerializedName("address") val address: String,
    @SerializedName("latitude") val latitude: Double,
    @SerializedName("longitude") val longitude: Double,
    @SerializedName("tags") val tags: List<String>,
    @SerializedName("price") val price: String,
    @SerializedName("hours") val hours: String,
    @SerializedName("open_hour") val openHour: Int,
    @SerializedName("close_hour") val closeHour: Int,
    @SerializedName("description") val description: String,
    @SerializedName("category") val category: String,
    @SerializedName("phone") val phone: String?,
    @SerializedName("website") val website: String?,
    @SerializedName("popular_dishes") val popularDishes: List<String>,
    @SerializedName("has_delivery") val hasDelivery: Boolean,
    @SerializedName("has_dine_in") val hasDineIn: Boolean,
    @SerializedName("has_takeaway") val hasTakeaway: Boolean,
    @SerializedName("image_url") val imageUrl: String?,
    @SerializedName("is_sponsored") val isSponsored: Boolean = false,
    @SerializedName("is_verified") val isVerified: Boolean = false,
    @SerializedName("contributor_id") val contributorId: String?
)

/** Convert a Supabase DTO to the app's domain model */
fun SupabaseShopDTO.toKebabShop(): KebabShop {
    return KebabShop(
        id = id,
        name = name,
        rating = rating,
        reviews = reviews,
        address = address,
        latitude = latitude,
        longitude = longitude,
        tags = tags,
        price = price,
        hours = hours,
        openHour = openHour,
        closeHour = closeHour,
        description = description,
        imageName = "",
        category = KebabCategory.fromDisplayName(category),
        phone = phone ?: "",
        website = website ?: "",
        popularDishes = popularDishes,
        hasDelivery = hasDelivery,
        hasDineIn = hasDineIn,
        hasTakeaway = hasTakeaway,
        isSponsored = isSponsored,
        isVerified = isVerified,
        contributorId = contributorId,
        imageUrl = imageUrl
    )
}
